version: "3"
services:

  proxy-service:
#    build: ./proxy
    build: .
    image : proxy-image
    container_name: proxy-container
    ports:
      - "80:80"
    restart: always
    networks:
      - frontend

networks:
  frontend: